name: CD

on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.1' # Replace with your Go version

      - name: Build app
        run: |
          chmod +x scripts/buildprod.sh
          ./scripts/buildprod.sh

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: notely-472720

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v3'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag europe-west3-docker.pkg.dev/notely-472720/notely-ar-repo/notely:v1 .
