name: CD

on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.1' # Replace with your Go version

      # Step 3: Build the app
      - name: Build app
        run: |
          chmod +x scripts/buildprod.sh
          ./scripts/buildprod.sh
