name: ci

on:
  pull_request:
    branches:
      - '**'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Run Go tests with coverage
        run: go test ./... -cover

  style:
    name: Style Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Run go fmt
        id: gofmt
        run: go fmt ./...

      - name: Ensure no formatting issues
        run: test -z "$(go fmt ./...)"

